---
- hosts: dev
  become: true
  
  tasks:
  - name: create file
    file:
      dest: /home/ec2-user/file1.txt
      state: touch
   
  - name: run kubectl command
    command: cat /home/ec2-user/file1.txt
    
